String teachername = "tess";
int dagePåÅret = 365;
String byNavn = "København";
boolean hovedstad = true;
int minutterPerDag = 60*24;
float startVægt = 22.12
String intro = "Hej, jeg heddder "+teachername;
boolean Positiv = false;
float kvadratmeter = 2.2 + 33;
char tøjStørrelse = 'S';
